# Test data for tfplan.

package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

filegroup(
    name = "testdata",
    srcs = [
        "plan.json",
        "state.json",
    ],
)
