load("//tools/build_defs/testing:bzl_library.bzl", "bzl_library")

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

bzl_library(
    name = "config_test_bzl",
    srcs = ["config_test.bzl"],
    parse_tests = False,
    visibility = ["//visibility:private"],
)
