"""An Apache Beam DoFn for untaring a tar file."""
import tarfile

import apache_beam as beam
import tensorflow as tf


class ReadTarFile(beam.DoFn):
  """Untar a tar file."""

  def process(self, path, path_to_key=lambda x: x):
    """Overrides beam.DoFn.process.

    Args:
      path: The full path to the tar file. This can be a GCS URI or a local
        path.
      path_to_key: A function that maps the relative path of the untar'd files
        to the returned key

    Yields:
      Tuple[Any, bytes]: the key generated by `path_to_key` and the file
      contents.
    """
    with tf.io.gfile.GFile(path) as gf:
      tar = tarfile.open(fileobj=gf, mode='r')
      for tar_info in tar:
        name = tar_info.name
        file_obj = tar.extractfile(tar_info)
        if file_obj is not None:
          file_bytes = file_obj.read()
          yield path_to_key(name), file_bytes
