# GCP Deployment Manager Templates used by the Cloud Healthcare deployment tools.

package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

filegroup(
    name = "templates",
    srcs = [
        "audit_log_config.py",
    ],
)
