package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["runner.go"],
    importpath = "github.com/GoogleCloudPlatform/healthcare/deploy/runner",
)
