load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "842ec0e6b4fbfdd3de6150b61af92901eeb73681fd4d185746644c338f51d4c0",
    urls = [
        "https://storage.googleapis.com/bazel-mirror/github.com/bazelbuild/rules_go/releases/download/v0.20.1/rules_go-v0.20.1.tar.gz",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.20.1/rules_go-v0.20.1.tar.gz",
    ],
)

http_archive(
    name = "bazel_gazelle",
    sha256 = "7fc87f4170011201b1690326e8c16c5d802836e3a0d617d8f75c3af2b23180c4",
    urls = ["https://github.com/bazelbuild/bazel-gazelle/releases/download/0.18.2/bazel-gazelle-0.18.2.tar.gz"],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_rules_dependencies", "go_register_toolchains")

go_rules_dependencies()

go_register_toolchains()

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")

gazelle_dependencies()

http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "14ac30773fdb393ddec90e158c9ec7ebb3f8a4fd533ec2abbfd8789ad81a284b",
    strip_prefix = "rules_docker-0.12.1",
    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.12.1/rules_docker-v0.12.1.tar.gz"],
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)

container_repositories()

load(
    "@io_bazel_rules_docker//go:image.bzl",
    go_image_repos = "repositories",
)

go_image_repos()

go_repository(
    name = "com_github_google_cmp",
    importpath = "github.com/google/go-cmp",
    tag = "v0.2.0",
)

go_repository(
    name = "com_github_mitchellh_hashstructure",
    importpath = "github.com/mitchellh/hashstructure",
    tag = "v1.0.0",
)

go_repository(
    name = "com_github_mitchellh_homedir",
    importpath = "github.com/mitchellh/go-homedir",
    tag = "v1.1.0",
)

go_repository(
    name = "com_github_imdario_mergo",
    importpath = "github.com/imdario/mergo",
    tag = "v0.3.7",
)

go_repository(
    name = "com_github_xeipuuv_gojsonschema",
    importpath = "github.com/xeipuuv/gojsonschema",
    tag = "v1.1.0",
)

go_repository(
    name = "com_github_xeipuuv_gojsonreference",
    commit = "bd5ef7bd5415a7ac448318e64f11a24cd21e594b",
    importpath = "github.com/xeipuuv/gojsonreference",
)

go_repository(
    name = "com_github_xeipuuv_gojsonpointer",
    commit = "4e3ac2762d5f479393488629ee9370b50873b3a6",
    importpath = "github.com/xeipuuv/gojsonpointer",
)

go_repository(
    name = "in_ghodss_yaml",
    commit = "25d852aebe32c875e9c044af3eef9c7dc6bc777f",
    importpath = "github.com/ghodss/yaml",
)

go_repository(
    name = "in_gopkg_yaml_v2",
    importpath = "gopkg.in/yaml.v2",
    tag = "v2.2.2",
)

http_archive(
    name = "terraform_google_forseti",
    build_file_content = """
filegroup(
  name = "all_files",
  srcs = glob(["**/*"]),
  visibility = ["//visibility:public"],
)""",
    sha256 = "e9d5d669a395b68d15118d74b96544fca0e5d19aed6aa2362eee4cb9040fba47",
    strip_prefix = "terraform-google-forseti-3.0.0",
    urls = ["https://github.com/forseti-security/terraform-google-forseti/archive/v3.0.0.tar.gz"],
)

load("@io_bazel_rules_docker//container:container.bzl", "container_pull")

# Cloud Build team maintained gcloud image.
# https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/gcloud
container_pull(
    name = "gcloud",
    digest = "sha256:1180ba5e78259cce05f0fe4b7d2f711af6a051af612d3f92938b6d7a1acf3992",
    registry = "gcr.io",
    repository = "cloud-builders/gcloud",
)

TERRAFORM_VERSION = "0.12.10"

http_archive(
    name = "terraform",
    build_file_content = """
filegroup(
  name = "executable",
  srcs = ["terraform"],
  visibility = ["//visibility:public"],
)""",
    sha256 = "2215208822f1a183fb57e24289de417c9b3157affbe8a5e520b768edbcb420b4",
    urls = ["https://releases.hashicorp.com/terraform/" + TERRAFORM_VERSION + "/terraform_" + TERRAFORM_VERSION + "_linux_amd64.zip"],
)
