# Description:
#    An application to demonstrate how to use the Healthcare FHIR APIs
package(default_visibility = ["//visibility:public"])

# Google-owned code that we licence under Apache.
licenses(["notice"])  # Apache 2.0

exports_files(["LICENSE"])
