# Test data for apply.

package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

filegroup(
    name = "testdata",
    srcs = [
        "project_with_remote_audit_logs_dryrun_commands.txt",
    ],
)
