# Test data for apply.

package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

filegroup(
    name = "testdata",
    srcs = [
        "minimal_dryrun_commands.txt",
    ],
)
