# Copyright 2019 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

projects:
- project_id: {{.CLOUDSANDBOX_PROJECT_ID}}
  owners_group: {{.USER}}_owner@{{.DOMAIN}}.com
  auditors_group: {{.USER}}_audit@{{.DOMAIN}}.com
  stackdriver_alert_email: {{.USER}}@{{.DOMAIN}}.com
  audit_logs:
    logs_gcs_bucket:
      properties:
        # The bucket name should be global unique, check the best practices:
        # https://cloud.google.com/storage/docs/best-practices#naming
        name: {{.CLOUD_SANDBOX_LOGS_BUCKET_ID}}
        location: US
        storageClass: MULTI_REGIONAL
      ttl_days: 365
    logs_bq_dataset:
      properties:
        # The bigquery dataset name does not allow any '-'.
        name: {{.CLOUD_SANDBOX_LOGS_DATASET_ID}}
        location: US
  enabled_apis:
  - bigquery-json.googleapis.com
  - cloudfunctions.googleapis.com
  - compute.googleapis.com
  - dataflow.googleapis.com
  - healthcare.googleapis.com
  - iam.googleapis.com
  - logging.googleapis.com
  - monitoring.googleapis.com
  - pubsub.googleapis.com
  - servicemanagement.googleapis.com
  - storage-api.googleapis.com
  - storage-component.googleapis.com
  - stackdriver.googleapis.com
  - stackdriverprovisioning.googleapis.com
  resources:
    service_accounts:
    - properties:
        accountId: {{.USER}}-dataflow
    iam_policies:
    - name: some_iam_policy
      properties:
        projectId: {{.CLOUDSANDBOX_PROJECT_ID}}
        roles:
        - role: "roles/bigquery.dataEditor"
          members: ["serviceAccount:$(ref.{{.USER}}-dataflow.email)"]
        - role: "roles/bigquery.jobUser"
          members: ["serviceAccount:$(ref.{{.USER}}-dataflow.email)"]
        - role: "roles/bigquery.user"
          members: ["serviceAccount:$(ref.{{.USER}}-dataflow.email)"]
        - role: "roles/cloudfunctions.developer"
          members: ["serviceAccount:$(ref.{{.USER}}-dataflow.email)"]
        - role: "roles/compute.viewer"
          members: ["serviceAccount:$(ref.{{.USER}}-dataflow.email)"]
        - role: "roles/dataflow.developer"
          members: ["serviceAccount:$(ref.{{.USER}}-dataflow.email)"]
        - role: "roles/dataflow.worker"
          members: ["serviceAccount:$(ref.{{.USER}}-dataflow.email)"]
        - role: "roles/iam.serviceAccountUser"
          members: ["serviceAccount:$(ref.{{.USER}}-dataflow.email)"]
        - role: "roles/storage.objectCreator"
          members: ["serviceAccount:$(ref.{{.USER}}-dataflow.email)"]
        - role: "roles/storage.objectViewer"
          members: ["serviceAccount:$(ref.{{.USER}}-dataflow.email)"]
    gcs_buckets:
    - properties:
        location: US
        name: chc-{{.CHS_NAME}}-fhir
        bindings:
        - role: roles/storage.objectAdmin
          members: ["serviceAccount:$(ref.{{.USER}}-dataflow.email)"]
    - properties:
        location: US
        name: chc-{{.CHS_NAME}}-raw
        bindings:
        - role: roles/storage.objectViewer
          members: ["serviceAccount:$(ref.{{.USER}}-dataflow.email)"]
    bq_datasets:
    - properties:
        name: chc_{{.CHS_NAME_UNDERSCORES}}_fhir
        location: US
        access:
        - role: WRITER
          userByEmail: $(ref.{{.USER}}-dataflow.email)
    pubsubs:
    - properties:
        topic: {{.CHS_NAME}}-hl7v2-topic
        subscriptions:
        - name: "{{.CHS_NAME}}-hl7v2-sub"
    chc_datasets:
    - properties:
        location: {{.DATASET_LOCATION}}
        datasetId: {{.CHS_NAME}}-health-ds
        hl7V2Stores:
        - hl7V2StoreId: {{.CHS_NAME}}-hl7v2-sub
          notificationConfig:
            pubsubTopic: $(ref.{{.CHS_NAME}}-hl7v2-topic.topicName)
        fhirStores:
        - fhirStoreId: {{.CHS_NAME}}-fhir-sub
    vpc_networks:
    - properties:
        name: data-harmonization-private
        autoCreateSubnetworks: false
        subnetworks:
          - name: data-harmonization-subnetwork
            region: us-central1
            ipCidrRange: "172.16.0.0/24"
            privateIpGoogleAccess: false
            enableFlowLogs: true
    gce_firewalls:
    - name: {{.CLOUDSANDBOX_PROJECT_ID}}-allow-ssh-access
      properties:
        network: '$(ref.data-harmonization-private.selfLink)'
        rules:
        - name: allow-tcp22
          allowed:
          - IPProtocol: tcp
            ports: ["22"]

    gce_instances:
    - properties:
        name: some-instance
        zone: us-central1-a
        diskImage: projects/coreos-cloud/global/images/family/coreos-stable
        diskSizeGb: 10
        machineType: n1-standard-1
        diskType: pd-standard
        network: $(ref.data-harmonization-private.selfLink)
        subnetwork: $(ref.data-harmonization-subnetwork.selfLink)
    gke_clusters:
    - properties:
        name: mllp-adapter-cluster
        clusterLocationType: Regional
        region: us-central1
        cluster:
          name: mllp-adapter-cluster
          description: 'MLLP Adapter'
          network: '$(ref.data-harmonization-private.selfLink)'
          subnetwork: '$(ref.data-harmonization-subnetwork.selfLink)'
          initialClusterVersion: '1.13.7-gke.8'
          initialNodeCount: 3
          locations: ['us-central1-b']
          nodeConfig:
            oauthScopes:
            - 'https://www.googleapis.com/auth/cloud-healthcare'
            - 'https://www.googleapis.com/auth/pubsub'
            - 'https://www.googleapis.com/auth/service.management.readonly'
            - 'https://www.googleapis.com/auth/servicecontrol'
    gke_workloads:
    - cluster_name: mllp-adapter-cluster
      properties:
        apiVersion: extensions/v1beta1
        kind: Deployment
        metadata:
          name: mllp-adapter-deployment
        spec:
          replicas: 1
          template:
            metadata:
              labels:
                app: mllp-adapter
            spec:
              containers:
                - name: mllp-adapter
                  imagePullPolicy: Always
                  image: gcr.io/cloud-healthcare-containers/mllp-adapter@sha256:latest
                  ports:
                    - containerPort: 2575
                      protocol: TCP
                      name: "port"
                  command:
                    - "/usr/mllp_adapter/mllp_adapter"
                    - "--port=2575"
                    - "--hl7_v2_project_id={{.CLOUDSANDBOX_PROJECT_ID}}"
                    - "--hl7_v2_location_id={{.DATASET_LOCATION}}"
                    - "--hl7_v2_dataset_id={{.CHS_NAME}}-health-ds"
                    - "--hl7_v2_store_id={{.CHS_NAME}}-hl7v2-sub"
                    - "--api_addr_prefix=https://healthcare.googleapis.com/v1beta1"
                    - "--receiver_ip=0.0.0.0"
                    - "--logtostderr"
